"""add github tracking models

Revision ID: 690ce9c38fbf
Revises: 20260904_01_related_links
Create Date: 2026-09-15 00:20:18.426271
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '690ce9c38fbf'
down_revision: Union[str, None] = '20260904_01_related_links'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_reports_generated_at'), 'github_reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_github_reports_report_type'), 'github_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_github_reports_status'), 'github_reports', ['status'], unique=False)
    op.create_table('github_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html_url', sa.String(length=2048), nullable=False),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('homepage', sa.String(length=2048), nullable=True),
    sa.Column('license_name', sa.String(length=100), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('watchers', sa.Integer(), nullable=False),
    sa.Column('repo_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repo_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('momentum_tier', sa.String(length=30), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_status', sa.String(length=30), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_repos_full_name'), 'github_repos', ['full_name'], unique=True)
    op.create_index(op.f('ix_github_repos_momentum_score'), 'github_repos', ['momentum_score'], unique=False)
    op.create_index(op.f('ix_github_repos_momentum_tier'), 'github_repos', ['momentum_tier'], unique=False)
    op.create_index(op.f('ix_github_repos_primary_language'), 'github_repos', ['primary_language'], unique=False)
    op.create_index(op.f('ix_github_repos_stars'), 'github_repos', ['stars'], unique=False)
    op.create_index(op.f('ix_github_repos_status'), 'github_repos', ['status'], unique=False)
    op.create_index(op.f('ix_github_repos_summary_status'), 'github_repos', ['summary_status'], unique=False)
    op.create_table('github_report_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('momentum_tier', sa.String(length=30), nullable=True),
    sa.Column('highlight', sa.Text(), nullable=True),
    sa.Column('star_delta_24h', sa.Integer(), nullable=True),
    sa.Column('star_delta_7d', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['github_repos.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['github_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_report_items_repo_id'), 'github_report_items', ['repo_id'], unique=False)
    op.create_index(op.f('ix_github_report_items_report_id'), 'github_report_items', ['report_id'], unique=False)
    op.create_table('github_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('watchers', sa.Integer(), nullable=False),
    sa.Column('star_delta_24h', sa.Integer(), nullable=True),
    sa.Column('star_delta_7d', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['github_repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'snapshot_at', name='uq_repo_snapshot_at')
    )
    op.create_index(op.f('ix_github_snapshots_repo_id'), 'github_snapshots', ['repo_id'], unique=False)
    op.create_index(op.f('ix_github_snapshots_snapshot_at'), 'github_snapshots', ['snapshot_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_snapshots_snapshot_at'), table_name='github_snapshots')
    op.drop_index(op.f('ix_github_snapshots_repo_id'), table_name='github_snapshots')
    op.drop_table('github_snapshots')
    op.drop_index(op.f('ix_github_report_items_report_id'), table_name='github_report_items')
    op.drop_index(op.f('ix_github_report_items_repo_id'), table_name='github_report_items')
    op.drop_table('github_report_items')
    op.drop_index(op.f('ix_github_repos_summary_status'), table_name='github_repos')
    op.drop_index(op.f('ix_github_repos_status'), table_name='github_repos')
    op.drop_index(op.f('ix_github_repos_stars'), table_name='github_repos')
    op.drop_index(op.f('ix_github_repos_primary_language'), table_name='github_repos')
    op.drop_index(op.f('ix_github_repos_momentum_tier'), table_name='github_repos')
    op.drop_index(op.f('ix_github_repos_momentum_score'), table_name='github_repos')
    op.drop_index(op.f('ix_github_repos_full_name'), table_name='github_repos')
    op.drop_table('github_repos')
    op.drop_index(op.f('ix_github_reports_status'), table_name='github_reports')
    op.drop_index(op.f('ix_github_reports_report_type'), table_name='github_reports')
    op.drop_index(op.f('ix_github_reports_generated_at'), table_name='github_reports')
    op.drop_table('github_reports')
    # ### end Alembic commands ###
